import fsUtils from "../utils/fsUtils.js";

// TODO: tailwindThemeExtension.cjs should have .js extension when type !== "module" in root package.json
const src = (projectPath: string) => `
import { generateTwThemeExtensions } from "./gen";
import defaultTheme from "../themes/default";

generateTwThemeExtensions(
  defaultTheme,
  "${projectPath}/${fsUtils.dirNames.twdBase}/${fsUtils.dirNames._autogenerated}/_variables.css",
  "${projectPath}/tailwindThemeExtension.cjs"
);
`;

export default src;
