import { ProjectType } from "../../types/projectType.js";
import fileExt from "../../utils/fileExt.js";
import fsUtils from "../../utils/fsUtils.js";

const src = (projectPath: string, type: ProjectType) => `
import { generateTwThemeExtensions } from "./gen${fileExt.getExt.ts(type)}";
import defaultTheme from "../themes/default${fileExt.getExt.ts(type)}";

generateTwThemeExtensions(
  defaultTheme,
  "${projectPath}/${fsUtils.dirNames.twdBase}/${
  fsUtils.dirNames._autogenerated
}/_variables.css",
  "${projectPath}/${fsUtils.dirNames.twdBase}/${
  fsUtils.dirNames._autogenerated
}/tw-designer.extends${fileExt.getExt.commonjs(type)}",
);
`;

export default src;
